#!/bin/bash

src_path=

if [ $# -eq 1 ]; then
    src_path=$1
fi
    
list_update() {
    git status | grep modified | awk '{print $2}'
}

pull_updates(){
    git pull $1
}

push_updates(){
    git add $1
    echo "git add $1"
    git commit -m "$2"
    git push -u origin master
}

echo "Updating awsv1"
pull_updates $src_path

filters=`ls -d filters/*/`
home_dir=`pwd`

for filter in $filters
do
    if [ $filter = "filters/sample/" ]; then
	continue;
    fi
    cd $filter
    echo "Updating $filter"
    if [ -n $src_path ]; then
	pull_updates $src_path/$filter
    else
	pull_updates
    fi
    
    cd "$home_dir"
done
