#!/bin/bash
. util.sh

caws genfltr sample fltr1
assert $?
caws genfltr sample fltr2
assert $? 
caws clock run
assert $?
caws gentbl sample tbl1
assert $?
caws gentbl sample tbl2
assert $? 
caws settbl sample tbl1 -f sample.json
assert $? 
caws settbl sample tbl2 -f sample2.json
assert $? 
caws gettbl tbl1
assert $? 
caws gettbl tbl2
assert $? 
caws gench sample ch1
assert $?
caws gench sample ch2
assert $? 
caws settblref tbl1 fltr1 tbl
assert $?
caws settblref tbl2 fltr2 tbl
assert $? 
caws setfltrpar fltr1 ch ch1 f64 1.0 u64 2 s64 3 f32 4.0 u32 5 s32 6 s16 7 u16 8 s8 9 u8 10 b n str hello e Bar
assert $?
caws setfltrpar fltr2 ch ch2 f64 11.0 u64 12 s64 13 f32 14.0 u32 15 s32 16 s16 17 u16 18 s8 19 u8 110 b y str world e Bar
assert $?
caws getfltrpar fltr1
assert $?
caws getfltrpar fltr2
assert $? "getfltrpar fltr2"
caws getfltrpar fltr1 ch f64 u64 s64 f32 u32 s32 s16 u16 s8 u8 b str e
assert $? "getfltrpar fltr1 misc"
caws getfltrpar fltr2 ch f64 u64 s64 f32 u32 s32 s16 u16 s8 u8 b str e
assert $? "getfltrpar fltr2 misc"
caws setfltrinchs fltr1 ch1 ch2
assert $?
caws setfltroutchs fltr1 ch2 ch1
assert $?
caws getfltrinchs fltr1
assert $?
caws getfltroutchs fltr1
assert $?
caws lstfltrs
assert $?
caws lsttbls
assert $?
caws lstchs
assert $?
caws run fltr1;
assert $?
caws run fltr2;
assert $?
sleep 2
caws settbl sample tbl1 -f sample2.json
assert $?
caws settbl sample tbl2 -f sample.json
assert $?
caws gettbl tbl1
assert $?
caws gettbl tbl2
assert $?
sleep 2
caws delfltr fltr1
nassert $?
caws delfltr fltr2
nassert $?
sleep 2
caws stop fltr1
assert $?
caws stop fltr2
assert $?
caws delfltr fltr1
assert $?
caws delfltr fltr2
assert $?
caws lstfltrs
assert $?
caws lsttbls
assert $?
caws lstchs
assert $?
caws deltbl tbl1
assert $?
caws deltbl tbl2
assert $?
exit 0
